#!/usr/bin/env bash
for i in {1..100}
do
	j=$(( i%3 ))
	k=$(( i%5 ))
	if [ $j -eq 0 ] && [ $k -eq 0 ]
	then
		echo "FizzBuzz"
	elif [ $j -eq 0 ]
	then
		echo "Fizz"
	elif [ $k -eq 0 ]
	then
		echo "Buzz"
	else
		echo $i
	i=$(( i+1 ))
done
