#!/usr/bin/env bash
#Write a Bash script that displays the content of the file /etc/passwd, only display username, user id, Home directory path for the user
fcontent="/etc/passwd"
while read -r fline
do
	cut -d: -f 1,2,6 "$fline"
done < $fcontent
