#!/usr/bin/env bash
#Write a Baxh script that groups visitors by IP and HTTP status code, and displays this data.
awk -F '.' '{ipcode1=$(( $1 )); ipcode2=$(( $2 )); ipcode3=$(( $3 )); ipcode4=$(( $4 )); ipcode5=$(( $5 )); countnum=0
awk -F '.' '{if($1==$ipcode1){if($2==$ipcode2){if($3==$ipcode3){if($4==$ipcode4){if($5==$ipcode5){countnum=$(( countnum+1 ))}}}}}}' apache-access.log
print $countnum" "$ipcode1"."$ipcode2"."$ipcode3"."$ipcode4" "$ipcode5}' apache-access.log
