#!/usr/bin/env bash
#Use while loop and case statement to display numbers from 1 to 20, and at 4th also display "bad luck from China"; at 9th also display "bad luck from Japan"; and at 17th also display "bad luck from Italy.
i=1
while [ $i -le 20]
do
	case $i in
		4) echo "4"
		   echo "bad luck from China"
	   	;;
     		9) echo "9"
		   echo "bad luck from Japan"
   		;;
		17) echo "17"
		    echo "bad luck from Italy"
    		;;
		$i) echo "$i"
		;;
	esac
	i=$(( i+1 ))
done	
