#!/usr/bin/env bash
#While loop nested in a while loop to display 12 hours and 59 minutes in each hour
h=0
m=1
while [ $h -le 12 ]
do
	echo "Hour: $h"
	while [ $m -le 59 ]
	do
		echo "$m"
		m=$(( m+1 ))
	done
	h=$(( h+1 ))
done
