#!/usr/bin/env bash
#Process and PID file

echo $$ > /var/run/myscript.pid
trap 'echo "I hate the kill command"' SIGTERM
trap 'echo "Y U no love me?"' SIGINT
trap 'kill -9 "$( pgrep -f "/var/run/myscript.pid" )" SIGQUIT SIGTERM
while true
do
	echo "To infinity and beyond"
done
