#!/usr/bin/env bash
#Bash init script manages manage_my_process, start, stop, restart

if [ "$1" == "start" ]
	./manage_my_process \
	&& echo $$ >> /var/run/my_process.pid \
        echo "manage_my_process started"	
elif [ "$1" == "stop" ]
	kill -9 "$( pgrep -f "./manage_my_process" )" \
	&& rm ./var/run/my_process.pid \
	&& echo "manage_my_process stopped"
elif [ "$1" == "restart" ]
	kill -9 "$( pgrep -f "./manage_my_process" )" \
	&& rm ./var/run/my_process.pid \
	&& ./manage_my_process \
	&& echo $$ >> /var/run/my_process.pid \
	&& echo "manage_my_process restarted"
else
echo "Usage: manage_my_process {start|stop|restart}"
