#!/usr/bin/env bash
#1.Display To infinity and beyond indefinitely. 2.With a sleep 2 in between each iteration. 3.Display I am invincible!!! when receiving a SIGTERM signal


trap 'echo "I am invincible!!!"' SIGTERM
while true
do
	echo "To infinity and beyond"
	sleep 2
done
